return {
    cmd = {
        "clangd",
        "--background-index",
        "--pch-storage=disk",
        "-j=8",
        "--clang-tidy",
        "--all-scopes-completion",
        "--function-arg-placeholders=0",
        "--completion-style=detailed",
        "--header-insertion=never",
        "--header-insertion-decorators",
        "--limit-results=1000",
        "--log=error",
        "--pretty",
    },
    filetypes = { "c", "cpp" },
    root_markers = { "compile_commands.json", "CMakeLists.txt", ".git" },
    capabilities = require("cmp_nvim_lsp").default_capabilities(),
}
